//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAction
    {
        public tblAction()
        {
            this.tblRoleActions = new HashSet<tblRoleAction>();
        }
    
        public int Id { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public int AppId { get; set; }
        public string Note { get; set; }
    
        public virtual tblApp tblApp { get; set; }
        public virtual ICollection<tblRoleAction> tblRoleActions { get; set; }
    }
}
